### PR TITLE
Configure bind

### PR DESCRIPTION
**Pull request by secobau**

### CODE REVIEW

**Comment by secobau** [comment]
> `man named`:
> 
> -c _config-file_
> Use _config-file_ as the configuration file instead of the default, _/etc/named.conf_. To ensure that reloading the configuration file continues to work after the server has changed its working directory due to to a possible directory option in the configuration file, config-file should be an absolute pathname.
> 
> We don't have `named.conf` in the default `named` path, so we need that option (even if the default path in Alpine is different from the documented one), don't we?

Maybe. I thought that as we are using the default path in alpine distribution bind package then it would not be necessary. But it is okay. It is only redundant in this case.

**Comment by secobau** [comment]
> I think named.conf & company should go in their standard paths, as they are standard files (not specialized docker or kubernetes files).
> 
> When we add docker/kube composes, we can decide how to handle secrets and configs.

Okay we can wait until the Docker compose file is ready.

**Comment by secobau** [comment]
> https://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.html#runRuntimeVariableData
> 
> 3.15. /run : Run-time variable data
> 3.15.1. Purpose
> 
> This directory contains system information data describing the system since it was booted. Files under this directory must be cleared (removed or truncated as appropriate) at the beginning of the boot process.
> 
> Configuration files shouldn't go in /run

These configuration files contain some confidential information. That is why they are injected to the container as **secrets**. 

**Secrets** are stored in memory instead of disk for security reasons. And Docker has chosen this place to be /run/secrets. There is nothing we can do about this unless stop using secrets.

One possible solution is to use a symlink from /var/bind to /run/secrets/var/bind if that better satisfies you.

**Comment by secobau** [comment]
> https://github.com/alejandro-colomar/dns.alejandro-colomar/blob/56e1176b63abec7975d2f6417ff7fbb00b9fa9f6/run/secrets/var/bind/master/10.168#L9
> 
> This project is not for the robot, but for the server named alejandro-colomar.

Not really.

We do not need any DNS for a web server. DNS are only useful for internal networks.

In rob_cam we have to solve the problem for the internal network. So it is a good idea to implement a custom DNS solution.

If you prefer so we can rename a new project as BIND and link it with rob_cam project.

I do not see the need for a DNS otherwise.

**Comment by alejandro-colomar** [comment]
If this PR is for rob_cam, then it should be pushed to rob_cam.  Also rob_cam is paused until july.

**Comment by secobau** [comment]
> If this PR is for rob_cam, then it should be pushed to rob_cam. rob_cam development is paused until july.

Indeed. I have already placed a comment in rob_cam asking to create a parent project to integrate all the necessary tools.

On the other hand we do not need to wait until July to fix this problem because:
1. It might be too late then to investigate and find solutions to old problems
1. We have already developed the solution
1. This solution can be reused in the current project if we happen to need some kind of DNS implementation

So that I propose to finish the task and resolve the issue with the current developed solution.

It would nevertheless be really useful to create a parent project to integrate all needed tools for rob_cam deployment. Maybe it should be a parent project because Swarm implementation is going to be shared between both sub-projects.

**Comment by alejandro-colomar** [comment]
> 
> 
> > If this PR is for rob_cam, then it should be pushed to rob_cam. rob_cam development is paused until july.
> 
> Indeed. I have already placed a comment in rob_cam asking to create a parent project to integrate all the necessary tools.

Push it to rob_cam, without other repos.

> 
> On the other hand we do not need to wait until July to fix this problem because:
> 
>     1. It might be too late then to investigate and find solutions to old problems

Not too late.

> 
>     2. We have already developed the solution
> 
>     3. This solution can be reused in the current project if we happen to need some kind of DNS implementation

Do we need a DNS for a web server?

**Comment by secobau** [comment]
> > > If this PR is for rob_cam, then it should be pushed to rob_cam. rob_cam development is paused until july.
> > 
> > 
> > Indeed. I have already placed a comment in rob_cam asking to create a parent project to integrate all the necessary tools.
> 
> Push it to rob_cam, without other repos.
> 
> > On the other hand we do not need to wait until July to fix this problem because:
> > ```
> > 1. It might be too late then to investigate and find solutions to old problems
> > ```
> 
> Not too late.
> 
> > ```
> > 2. We have already developed the solution
> > 
> > 3. This solution can be reused in the current project if we happen to need some kind of DNS implementation
> > ```
> 
> Do we need a DNS for a web server?

Maybe. If there is an internal network in our solution.

**Pull request closed without merging**
